name: Helm E2E on Terraform Cloud

on:
  # schedule:
  #   - cron: '30 6 * * *'
  # pull_request:
  #   branches:
  #     - main
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  KUBECONFIG: ${{ github.workspace }}/.kube/config
  USE_EXISTING_CLUSTER: true
  DOCKER_IMAGE: 'this'
  DOCKER_REGISTRY: 'localhost:5000/v2/this'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: docker
        run: |
          docker ps
